version: '3.9'
services:
  foreignexchangerates.api:
    image: foreignexchangerates.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"